#pragma once
#ifndef  RESOURCE_H
#define RESOURCE_H
#define GAME_WIDTH 32*20
#define GAME_HEIGHT 800
#define BACKGROUND_HEIGHT 71
#define BITMAP_HEIGHT 32
#define BITMAP_WIDTH 32
#define NUM_BARRIER 4
#define NUM_ENEMY 30
#define BULLET_INTERVAL 50
#define WALL 20
enum IMG_RES
{
	INFO_PLAYER,
	INFO_ENEMY1,
	INFO_ENEMY1_b,
	INFO_ENEMY2,
	INFO_ENEMY2_b,
	INFO_ENEMY3,
	INFO_ENEMY3_b,
	INFO_UFO,
	INFO_BOOM1,
	INFO_BOOM2,
	INFO_BOOM3,
	INFO_BACKGROUND,
	INFO_BULLET,
	INFO_BULLET_B,
	INFO_BULLET2,
	INFO_BULLET2_B,
	INFO_START,
	INFO_STRINGEND,
	INFO_BARRIER,
	INT_1,
	INT_2,
	INT_3,
	INT_4,
	INT_5,
	INT_6,
	INT_7,
	INT_8,
	INT_9,
	INT_0,
	INFO_END
};
#endif
